services:
  - type: web
    name: rahati-platform
    env: docker
    plan: free
    buildCommand: ""
    startCommand: >
      php artisan config:cache &&
      php artisan migrate --force &&
      apache2-foreground
    rootDir: rahati
